### PR TITLE
Add blog post about new PHP plugin, upcoming v0.8.0 (alpha) release, and the future of LT development

### PR DESCRIPTION
**Pull request by kenny-evitt**
Contents:
1. The new PHP plugin
2. The upcoming v0.8.0 (alpha) release
3. Ongoing development of LT

For [2], we should also include some brief info about the v0.8.0 _stable_ release, e.g. an outline of the process for that to be completed.

For [3], I mainly wanted to describe the change in the core contributors and set expectations about ongoing development, e.g. that contributions will probably exclusively consist of changes contributors want to work on.

### CODE REVIEW

**Comment by kenny-evitt** [comment]
@thierrymarianne Want me to mention anything in particular about what's supported in the v0.0.1 version of the PHP plugin? Or what you want to implement next? Or what kinds of contributions you're interested in?

**Comment by kenny-evitt** [comment]
@cldwalker @rundis I figured it would be nice to finally add a post to the blog, even if we're still not done with the alpha release. Please let me know what you'd like me to include, e.g. any exciting details about yourself that you'd like users to know.

**Comment by cldwalker** [comment]
Thanks for taking the initiative Kenny but I think we should hold off on this. As is in [our checklist](https://github.com/LightTable/LightTable/issues/1936#issue-92653665), the plan is to do a blog post once 0.8.0 is released. Especially since this alpha release won't have a smooth OSX install I'd rather not deal with confused OSX users

**Comment by kenny-evitt** [comment]
@cldwalker All right, I'll hold off on this.

**Comment by kenny-evitt** [comment]
@cldwalker Just to be clear, in this post I wanted to announce the PHP plugin, describe the progress of the 0.8.0 alpha release, and also briefly describe the change in the team and the change in our focus. This wasn't intended to announce the release itself – as in it being released – just that we're still working on it.

**Comment by cldwalker** [comment]
Closing as alpha has already been released

**Pull request closed without merging**
