### PR TITLE
fix button hover status

### PR DESCRIPTION
**Pull request by mittya**

### CODE REVIEW

**Comment by cldwalker** [comment]
The download button [looks fine](https://www.dropbox.com/s/cybypm4kmfdqbv9/Screenshot%202014-10-20%2012.53.58.png?dl=0) on osx 10.9 and chrome. Can you provide a screenshot of what's broken on your browser and operating system?

**Comment by ibdknox** [comment]
It's subtle, but he's right in the hover case it shows the clicked state.

**Comment by mittya** [comment]
Yep, the background-position "0 -47px" is hover state, "0 -94px" is active state :)

**Comment by ibdknox** [comment]
Thanks for the PR! :)

**Pull request merged**
